// flow-typed signature: 69bfcfd565640d93fff3198c8c177788
// flow-typed version: <<STUB>>/mysql-easier_v^2.0.2/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'mysql-easier'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'mysql-easier' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'mysql-easier/lib/demo' {
  declare module.exports: any;
}

declare module 'mysql-easier/lib/index' {
  declare module.exports: any;
}

declare module 'mysql-easier/lib/mysql-connection' {
  declare module.exports: any;
}

declare module 'mysql-easier/lib/mysql-pool' {
  declare module.exports: any;
}

declare module 'mysql-easier/lib/sql-util' {
  declare module.exports: any;
}

declare module 'mysql-easier/lib/sql-util.test' {
  declare module.exports: any;
}

declare module 'mysql-easier/lib/transaction-demo' {
  declare module.exports: any;
}

declare module 'mysql-easier/src/demo' {
  declare module.exports: any;
}

declare module 'mysql-easier/src/index' {
  declare module.exports: any;
}

declare module 'mysql-easier/src/mysql-connection' {
  declare module.exports: any;
}

declare module 'mysql-easier/src/mysql-pool' {
  declare module.exports: any;
}

declare module 'mysql-easier/src/sql-util' {
  declare module.exports: any;
}

declare module 'mysql-easier/src/sql-util.test' {
  declare module.exports: any;
}

declare module 'mysql-easier/src/transaction-demo' {
  declare module.exports: any;
}

// Filename aliases
declare module 'mysql-easier/lib/demo.js' {
  declare module.exports: $Exports<'mysql-easier/lib/demo'>;
}
declare module 'mysql-easier/lib/index.js' {
  declare module.exports: $Exports<'mysql-easier/lib/index'>;
}
declare module 'mysql-easier/lib/mysql-connection.js' {
  declare module.exports: $Exports<'mysql-easier/lib/mysql-connection'>;
}
declare module 'mysql-easier/lib/mysql-pool.js' {
  declare module.exports: $Exports<'mysql-easier/lib/mysql-pool'>;
}
declare module 'mysql-easier/lib/sql-util.js' {
  declare module.exports: $Exports<'mysql-easier/lib/sql-util'>;
}
declare module 'mysql-easier/lib/sql-util.test.js' {
  declare module.exports: $Exports<'mysql-easier/lib/sql-util.test'>;
}
declare module 'mysql-easier/lib/transaction-demo.js' {
  declare module.exports: $Exports<'mysql-easier/lib/transaction-demo'>;
}
declare module 'mysql-easier/src/demo.js' {
  declare module.exports: $Exports<'mysql-easier/src/demo'>;
}
declare module 'mysql-easier/src/index.js' {
  declare module.exports: $Exports<'mysql-easier/src/index'>;
}
declare module 'mysql-easier/src/mysql-connection.js' {
  declare module.exports: $Exports<'mysql-easier/src/mysql-connection'>;
}
declare module 'mysql-easier/src/mysql-pool.js' {
  declare module.exports: $Exports<'mysql-easier/src/mysql-pool'>;
}
declare module 'mysql-easier/src/sql-util.js' {
  declare module.exports: $Exports<'mysql-easier/src/sql-util'>;
}
declare module 'mysql-easier/src/sql-util.test.js' {
  declare module.exports: $Exports<'mysql-easier/src/sql-util.test'>;
}
declare module 'mysql-easier/src/transaction-demo.js' {
  declare module.exports: $Exports<'mysql-easier/src/transaction-demo'>;
}
